officers/urls.py
"""URL configuration for the gtphipsi.officers package.

All URIs beginning with '/officers/' are routed to this URL configuration.

"""

from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('gtphipsi.officers.views',
    ## ============================================= ##
    ##                 Public Pages                  ##
    ## ============================================= ##
    url(r'^$', 'officers', name='show_officers'),

    ## ============================================= ##
    ##              Authenticated Pages              ##
    ## ============================================= ##
    url(r'^add/$', 'add_officer', name='add_officer'),
    url(r'^history/$', 'officer_history', name='officer_history'),
    url(r'^(?P<office>G?P|VGP|[A|B|S]G|Hod|H[i|M]|Phu|IFC)/edit/$', 'edit_officer', name='edit_officer'),
    url(r'^(?P<office>G?P|VGP|[A|B|S]G|Hod|H[i|M]|Phu|IFC)/history/$', 'office_history', name='office_history'),
    url(r'^(?P<office>G?P|VGP|[A|B|S]G|Hod|H[i|M]|Phu|IFC)/history/add/$', 'add_office_history', name='add_office_history'),
)

rest/v1/officers/urls.py
from django.conf.urls.defaults import patterns, url
from rest.v1.officers.views import OfficerDetails, OfficerList, OfficerHistoryList


urlpatterns = patterns('gtphipsi.rest.v1.officers.views',
    url(r'^$', OfficerList.as_view(), name='officer_list'),
    url(r'^(?P<office>G?P|VGP|[A|B|S]G|Hod|H[i|M]|Phu|IFC)/$', OfficerDetails.as_view(), name='officer_details'),
    url(r'^(?P<office>G?P|VGP|[A|B|S]G|Hod|H[i|M]|Phu|IFC)/history/$', OfficerHistoryList.as_view(), name='officer_history')
)

urls.py
"""Root URL configuration for the gtphipsi web application.

All URIs are routed to this URL configuration, then possibly dispatched to other URL confs in this package's submodules.

"""

from django.conf.urls.defaults import patterns, url, include
from django.views.generic.simple import direct_to_template


# 'Global' pages. These are pages that don't fit neatly into one app (submodule) or another.
urlpatterns = patterns('gtphipsi.views',
    url(r'^$', 'home', name='home'),
    url(r'^login/$', 'sign_in', name='sign_in'),
    url(r'^logout/$', 'sign_out', name='sign_out'),
    url(r'^register/$', 'register', name='register'),
    url(r'^register/success/$', 'register_success', name='register_success'),
    url(r'^calendar/$', 'calendar', name='calendar'),
    url(r'^contact/$', 'contact', name='contact'),
    url(r'^contact/thanks/$', 'contact_thanks', name='contact_thanks'),
    url(r'^forbidden/$', 'forbidden', name='forbidden'),
    url(r'^forgot/$', 'forgot_password', name='forgot_password'),
    url(r'^reset/(?P<id>\d+)/$', 'reset_password', name='reset_password'),
    url(r'^reset/success/$', 'reset_password_success', name='reset_password_success'),
    url(r'^robots\.txt$', direct_to_template, {'template': 'robots.txt', 'mimetype': 'text/plain'}),
)

# Include other URL configurations for app-specific pages.
urlpatterns += patterns('',
     url(r'^brothers/', include('gtphipsi.brothers.urls')),
     url(r'^officers/', include('gtphipsi.officers.urls')),
     url(r'^rush/', include('gtphipsi.rush.urls')),
     url(r'^chapter/', include('gtphipsi.chapter.urls')),
     url(r'^forums/', include('gtphipsi.forums.urls')),
     url(r'^rest/v1/', include('gtphipsi.rest.v1.urls')),
)

# Hack - to continue to support the old rush schedule URI.
urlpatterns += patterns('gtphipsi.rush.views',
    url(r'^rushschedule\.php$', 'old_schedule', name='old_rush_schedule'),
)

officers/models.py
"""Models for the gtphipsi.officers package.

This module exports the following model classes:
    - ChapterOfficer
    - OfficerHistory

This module exports the following tuples of field choices:
    - OFFICER_CHOICES

"""

from django.db import models

from gtphipsi.brothers.models import UserProfile


# List of officer positions within the chapter.
OFFICER_CHOICES = (
    ('GP', 'President'),
    ('VGP', 'Vice President'),
    ('P', 'Treasurer'),
    ('AG', 'Corresponding Secretary'),
    ('BG', 'Recording Secretary'),
    ('SG', 'Historian'),
    ('Hod', 'Messenger'),
    ('Phu', 'Sergeant at Arms'),
    ('Hi', 'Chaplain'),
    ('IFC', 'IFC Representative'),
#    ('HM', 'House Manager')
)


class ChapterOfficer(models.Model):
    """A current officer of the chapter, associating an undergraduate brother with an officer position."""

    office = models.CharField(choices=OFFICER_CHOICES, max_length=3)
    brother = models.ForeignKey(UserProfile, related_name='offices')
    updated = models.DateField()


class OfficerHistory(models.Model):
    """A historical record of officer positions, tracking which brothers held which officer positions in the past."""

    office = models.CharField(choices=OFFICER_CHOICES, max_length=3)
    brother = models.ForeignKey(UserProfile, related_name='former_offices')
    start = models.DateField(verbose_name='Start date')
    end = models.DateField(verbose_name='End date')

officers/views.py
"""View functions for the gtphipsi.officers package.

This module exports the following view functions:
    - officers (request)
    - edit_officer (request)
    - add_officer (request)
    - officer_history (request)
    - office_history (request, office)
    - add_office_history (request, office)

"""

from datetime import date
import logging

from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext

from gtphipsi.brothers.models import UserProfile
from gtphipsi.common import log_page_view
from gtphipsi.messages import get_message
from gtphipsi.officers.forms import OfficerForm, OfficerHistoryForm
from gtphipsi.officers.models import ChapterOfficer, OfficerHistory, OFFICER_CHOICES


log = logging.getLogger('django')


## ============================================= ##
##                                               ##
##                 Public Views                  ##
##                                               ##
## ============================================= ##


def officers(request):
    """Render a listing of the chapter's current officers."""
    log_page_view(request, 'Officer List')
    officers = []
    incomplete = False
    for key, value in OFFICER_CHOICES:  # retrieving records individually is inefficient, but it does sort by office
        try:
            officer = ChapterOfficer.objects.get(office=key)
        except ChapterOfficer.DoesNotExist:
            incomplete = True
        else:
            officers.append(officer)
    return render(request, 'officers/officers.html', {'officers': officers, 'add': incomplete},
                  context_instance=RequestContext(request))




## ============================================= ##
##                                               ##
##              Authenticated Views              ##
##                                               ##
## ============================================= ##


@login_required
@permission_required('officers.change_chapterofficer', login_url=settings.FORBIDDEN_URL)
def edit_officer(request, office):
    """Render and process a form to modify which brother currently holds an officer position.

    Required parameters:
        - office    =>  the abbreviation of the office to edit as a string (e.g., 'GP')

    """

    log_page_view(request, 'Edit Officer')
    title = _get_office_title_or_404(office)

    if request.method == 'POST':
        form = OfficerForm(request.POST)
        if form.is_valid():
            brother = form.cleaned_data.get('brother')
            try:
                prev = ChapterOfficer.objects.get(office=office)
            except ChapterOfficer.DoesNotExist:     # this shouldn't happen, but handle it just in case
                officer = ChapterOfficer.objects.create(office=office, brother=brother, updated=date.today())
                officer.save()
            else:
                if prev.brother != brother:
                    history = OfficerHistory.objects.create(office=prev.office, brother=prev.brother, start=prev.updated, end=date.today())
                    history.save()
                    prev.brother = brother  # just update the existing officer record instead of deleting and recreating
                    prev.updated = date.today()
                    prev.save()
                    log.info('%s (%s) changed %s from %s (#%d) to %s (#%d)', request.user.username, request.user.get_full_name(),
                             office, history.brother.common_name(), history.brother.badge, brother.common_name(), brother.badge)
            return HttpResponseRedirect(reverse('show_officers'))
    else:
        form = OfficerForm()

    return render(request, 'officers/edit_officer.html', {'form': form, 'title': title, 'office': office},
                  context_instance=RequestContext(request))


@login_required
@permission_required('officers.add_chapterofficer', login_url=settings.FORBIDDEN_URL)
def add_officer(request):
    """Render and process a form for administrators to add chapter officers (until all offices are added)."""

    log_page_view(request, 'Add Officer')
    error = None
    if request.method == 'POST':
        office = request.POST.get('office')
        found = False
        for key, value in OFFICER_CHOICES:
            if key == office:
                found = True
                break
        if found and not ChapterOfficer.objects.filter(office=office).count():
            badge = int(request.POST.get('brother'))
            try:
                brother = UserProfile.objects.get(badge=badge)
            except UserProfile.DoesNotExist:
                error = get_message('officer.brother.invalid')
            else:
                officer = ChapterOfficer.objects.create(office=office, brother=brother, updated=date.today())
                officer.save()
                return HttpResponseRedirect(reverse('show_officers'))
        else:
            error = get_message('officer.office.invalid')

    missing = []
    for key, value in OFFICER_CHOICES:
        try:
            ChapterOfficer.objects.get(office=key)
        except ChapterOfficer.DoesNotExist:
            missing.append((key, value))
    if not len(missing):
        return HttpResponseRedirect(reverse('forbidden'))   # all offices have already been added

    brothers = []
    for brother in UserProfile.objects.filter(status='U'):
        brothers.append((brother.badge, brother.common_name()))

    return render(request, 'officers/add_officer.html', {'offices': missing, 'brothers': brothers, 'error': error},
                  context_instance=RequestContext(request))


@login_required
def officer_history(request):
    """Render a listing of office names from which users may choose to see the history for an office."""
    log_page_view(request, 'Officer History')
    return render(request, 'officers/officer_history.html', context_instance=RequestContext(request))


@login_required
def office_history(request, office):
    """Render a listing of brothers who have held an officer position in the past, including the current officer.

    Required parameters:
        - office    =>  the abbreviation of the office whose history to view as a string (e.g., 'GP')

    """

    log_page_view(request, 'Office History')
    title = _get_office_title_or_404(office)

    history = []
    try:
        current = ChapterOfficer.objects.get(office=office)
    except ChapterOfficer.DoesNotExist:
        pass
    else:
        history.append((current.brother, current.updated, None))

    has_more = (OfficerHistory.objects.filter(office=office).count() > 9)
    show_all = (has_more and 'full' in request.GET and request.GET.get('full') == 'true')
    if has_more and show_all:
        old_officers = OfficerHistory.objects.filter(office=office).order_by('-end')
        has_more = False
    else:
        old_officers = OfficerHistory.objects.filter(office=office).order_by('-end')[:9]
    for officer in old_officers:
        history.append((officer.brother, officer.start, officer.end))

    return render(request, 'officers/office_history.html',
                  {'office': title, 'history': history, 'more': has_more, 'abbrev': office},
                  context_instance=RequestContext(request))


@login_required
@permission_required('officers.add_officerhistory', login_url=settings.FORBIDDEN_URL)
def add_office_history(request, office):
    """Render and process a form to create a new officer history record.

    Required parameters:
        - office    =>  the abbreviation of the office whose history to add as a string (e.g., 'GP')

    """
    log_page_view(request, 'Add Office History')
    title = _get_office_title_or_404(office)
    if request.method == 'POST':
        form = OfficerHistoryForm(request.POST)
        if form.is_valid():
            history = form.save(commit=False)
            history.office = office
            history.save()
            log.info('%s (%s) added history for %s: %s (#%d), %s - %s', request.user.username, request.user.get_full_name(),
                     office, history.brother.common_name(), history.brother.badge, history.start.strftime('%m/%d/%Y'),
                     history.end.strftime('%m/%d/%Y'))
            return HttpResponseRedirect(reverse('office_history', kwargs={'office': office}))
    else:
        form = OfficerHistoryForm()
    return render(request, 'officers/add_office_history.html', {'office': title, 'abbrev': office, 'form': form},
                  context_instance=RequestContext(request))






## ============================================= ##
##                                               ##
##               Private Functions               ##
##                                               ##
## ============================================= ##


def _get_office_title_or_404(abbrev):
    """Return the title of the office corresponding to the given abbreviation; raise Http404 if no such office exists."""
    for key, value in OFFICER_CHOICES:
        if key == abbrev:
            return value
    raise Http404

rest/v1/officers/views.py
from django.shortcuts import get_object_or_404

from rest_framework.permissions import IsAuthenticated

from gtphipsi.officers.models import ChapterOfficer, OfficerHistory
from gtphipsi.rest.v1.officers.serializers import OfficerSerializer, OfficerHistorySerializer
from gtphipsi.rest.v1.views import RequestAwareListAPIView, RequestAwareRetrieveAPIView


class OfficerList(RequestAwareListAPIView):
    queryset = ChapterOfficer.objects.all()
    serializer_class = OfficerSerializer


class OfficerDetails(RequestAwareRetrieveAPIView):
    queryset = ChapterOfficer.objects.all()
    serializer_class = OfficerSerializer

    def get_instance(self, **kwargs):
        return get_object_or_404(self.get_serializer_class().Meta.model, office=kwargs['office'])


class OfficerHistoryList(RequestAwareRetrieveAPIView):
    queryset = OfficerHistory.objects.all()
    serializer_class = OfficerHistorySerializer
    permission_classes = (IsAuthenticated,)

    def get_instance(self, **kwargs):
        return OfficerHistory.objects.filter(office=kwargs['office'])

templates/officers/add_office_history.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Add Office History | {{ block.super }}
{% endblock %}

{% block sidebar %}
    <h3>Note</h3>
    <p>Enter complete dates (e.g., "2/19/1852") for the start and end dates, but don't worry about getting the day of the month
    exactly right. Only the month and year will be shown.</p>
{% endblock %}

{% block content %}
    <h1>Add Office History</h1>
    <p>Use the form below to add a record of a past {{ office }}. Click "Add" when you are finished.</p>
    <form action="{% url 'gtphipsi.officers.views.add_office_history' office=abbrev %}" method="post">
        {% include "snippets/_table_form.html" with submit_text="Add" %}
    </form>
{% endblock %}

templates/officers/add_officer.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Add Officer | {{ block.super }}
{% endblock %}

{% block head_extras %}
    {{ block.super }}
    <style type="text/css">
        #content form {
            padding-left: 10px;
        }
        #content form ul li {
            list-style-type: none;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>Add Officer</h1>
    <p>Use the form below to add an officer. Click "Add" when you are finished.</p>
    {% if error %}
        <p><span class="error">{{ error }}</span></p>
    {% endif %}
    <form action="{% url 'gtphipsi.officers.views.add_officer' %}" method="post">
        {% csrf_token %}
        <table class="form">
            <tbody>
                <tr>
                    <td class="spaced">
                        <label for="office">Office</label>
                    </td>
                    <td class="spaced">
                        <select id="office" name="office">
                        {% for abbrev, title in offices %}
                            <option value="{{ abbrev }}">{{ title }}</option>
                        {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="spaced">
                        <label for="brother">Brother</label>
                    </td>
                    <td class="spaced">
                        <select id="brother" name="brother">
                        {% for badge, name in brothers %}
                            <option value="{{ badge }}">{{ name }} ... {{ badge }}</option>
                        {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input class="submit" type="submit" value="Add" />
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
{% endblock %}

templates/officers/edit_officer.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Update {{ title }} | {{ block.super }}
{% endblock %}

{% block head_extras %}
    {{ block.super }}
    <style type="text/css">
        #content form {
            padding-left: 10px;
        }
        #content form ul li {
            list-style-type: none;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>Update {{ title }}</h1>
    <p>Use the form below to update an officer position. Click "Save" when you are finished.</p>
    <form action="{% url 'gtphipsi.officers.views.edit_officer' office=office %}" method="post">
        {% include "snippets/_table_form.html" with submit_text="Save" %}
    </form>
{% endblock %}

templates/officers/office_history.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Officer History - {{ office }} | {{ block.super }}
{% endblock %}

{% block head_extras %}
    {{ block.super }}
    <style type="text/css">
        table.list {
            margin: 30px 10px;
        }
        table.list tbody tr td.dash {
            padding: 0 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>Officer History for {{ office }}</h1>
    {% ifequal history|length 0 %}
        <p style="margin-top: 20px">There is no information available on the position of {{ office }}.</p>
    {% else %}
    <p>The following is a list of the most recent brothers who have held the office of {{ office }}, starting with the current officer.
        {% if more %}
            The first ten names are shown. <span class="small"><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office=abbrev %}?full=true">show all</a></span>
        {% endif %}
    </p>
    <table class="list">
        <thead>
            <tr class="heading">
                <td class="left">#</td>
                <td class="middle">Brother</td>
                <td class="right" colspan=3>Date Range</td>
            </tr>
        </thead>
        <tbody>
            {% for brother, start, end in history %}
            <tr>
                <td class="left center">{{ forloop.revcounter }}</td>
                <td class="middle"><a class="hovercolor" href="{% url 'gtphipsi.brothers.views.show' badge=brother.badge %}">{{ brother.common_name }} ... {{ brother.badge }}</a></td>
                <td class="right">{{ start|date:"F Y" }}</td>
                <td class="dash">&mdash;</td>
                <td>{% if end %}{{ end|date:"F Y" }}{% else %}present{% endif %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endifequal %}
    {% if 'add_officerhistory' in group_perms %}
        <p><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.add_office_history' office=abbrev %}">new history record</a></p>
    {% endif %}
{% endblock %}

templates/officers/officer_history.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Officer History | {{ block.super }}
{% endblock %}

{% block head_extras %}
    {{ block.super }}
    <style type="text/css">
        #content table tbody tr td {
            width: 230px;
            height: 50px;
            font-size: 1.2em;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>Officer History</h1>
    <p>Select an office to view a list of brothers who have held that office in the past.</p>
    <table>
        <tbody>
            <tr>
                <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='GP' %}">President</a></td>
                <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='VGP' %}">Vice President</a></td>
            </tr>
            <tr>
                <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='P' %}">Treasurer</a></td>
                <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='AG' %}">Corresponding Secretary</a></td>
            </tr>
            <tr>
                <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='BG' %}">Recording Secretary</a></td>
                <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='SG' %}">Historian</a></td>
            </tr>
            <tr>
                <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='Hod' %}">Messenger</a></td>
                <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='Phu' %}">Sergeant at Arms</a></td>
            </tr>
            <tr>
                <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='Hi' %}">Chaplain</a></td>
                <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='IFC' %}">IFC Representative</a></td>
            </tr>
            {% comment %}
                <tr>
                    <td><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.office_history' office='HM' %}">House Manager</a></td>
                </tr>
            {% endcomment %}
        </tbody>
    </table>
{% endblock %}

templates/officers/officers.html
{% extends "base.html" %}
{% load static %}
{% load url from future %}

{% block title %}
    Chapter Officers | {{ block.super }}
{% endblock %}

{% block head_extras %}
    {% if user_profile %}
        <link href="{{ STATIC_URL }}styles/bros_only.css" rel="stylesheet" type="text/css" media="screen" />
    {% endif %}
    <style type="text/css">
        table.list {
            margin: 30px 10px 15px 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>Chapter Officers</h1>
    {% ifequal officers|length 0 %}
        {% if 'add_chapterofficer' in group_perms %}
            <p style="margin-top: 20px">
                <span class="error">No officer positions have been added yet. Click <a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.add_officer' %}">here</a> to add new officers.</span>
            </p>
        {% else %}
            <p style="margin-top: 20px">The chapter currently has not provided any information about her officers. Please check back later.</p>
        {% endif %}
    {% else %}
        <p>The following is a list of officer positions within the chapter, along with the name of the brother who currently holds that position.</p>
        {% if 'change_chapterofficer' in group_perms %}
            <p>To update an officer position, click "edit" next to the name of the office you wish to change.</p>
            {% if add %}
                <p><span class="error"><strong>NOTE:</strong> Some officer positions have not yet been added. Click <a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.add_officer' %}">here</a> to add new officers.</span></p>
            {% endif %}
        {% endif %}
        <table class="list">
            <thead>
                <tr class="heading">
                    <td class="left">Office</td>
                    <td class="right">Current Officer</td>
                </tr>
            </thead>
            <tbody>
            {% for officer in officers %}
                <tr>
                    <td class="left">
                        {{ officer.get_office_display }}
                        {% if 'change_chapterofficer' in group_perms %}
                            <span class="small"><a class="alwaysgreen" href="{% url 'gtphipsi.officers.views.edit_officer' office=officer.office %}">edit</a></span>
                        {% endif %}
                    </td>
                    <td class="right"><a class="hovercolor" href="{% url 'gtphipsi.brothers.views.show' badge=officer.brother.badge %}">{{ officer.brother.common_name }} ... {{ officer.brother.badge }}</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endifequal %}
    {% if add %}
        <p></p>
    {% endif %}
{% endblock %}