brothers/urls.py
"""URL configuration for the gtphipsi.brothers package.

All URIs beginning with '/brothers/' are routed to this URL configuration.

"""

from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('gtphipsi.brothers.views',
    ## ============================================= ##
    ##                 Public Pages                  ##
    ## ============================================= ##
    url(r'^$', 'list', name='brothers_list'),
    url(r'^(?P<badge>\d+)/$', 'show', name='view_profile'),
    url(r'^email/$', 'change_email', name='change_email'),
    url(r'^email/success/$', 'change_email_success', name='change_email_success'),

    ## ============================================= ##
    ##              Authenticated Pages              ##
    ## ============================================= ##
    url(r'^profile/$', 'my_profile', name='my_profile'),
    url(r'^manage/$', 'manage', name='manage_users'),
    url(r'^add/$', 'add', name='add_user'),
    url(r'^edit/$', 'edit', name='edit_profile'),
    url(r'^account/$', 'edit_account', name='edit_my_account'),
    url(r'^(?P<badge>\d+)/account/$', 'edit_account', name='edit_account'),
    url(r'^(?P<badge>\d+)/unlock/$', 'unlock', name='unlock_account'),
    url(r'^password/$', 'change_password', name='change_password'),
    url(r'^password/success/$', 'change_password_success', name='change_password_success'),
    url(r'^groups/$', 'manage_groups', name='manage_groups'),
    url(r'^groups/add/$', 'add_group', name='add_group'),
    url(r'^groups/(?P<id>\d+)/$', 'show_group', name='view_group'),
    url(r'^groups/(?P<id>\d+)/perms/$', 'edit_group_perms', name='edit_group_perms'),
    url(r'^groups/(?P<id>\d+)/members/$', 'edit_group_members', name='edit_group_members'),
    url(r'^groups/(?P<id>\d+)/delete/$', 'delete_group', name='delete_group'),
    url(r'^privacy/$', 'visibility', name='visibility'),
    url(r'^privacy/public/$', 'edit_public_visibility', name='edit_public_visibility'),
    url(r'^privacy/chapter/$', 'edit_chapter_visibility', name='edit_chapter_visibility'),
    url(r'^notifications/$', 'edit_notification_settings', name='notification_settings'),
)

rest/v1/brothers/urls.py
from django.conf.urls.defaults import patterns, url

from gtphipsi.rest.v1.brothers.views import AlumnusList, BrotherDetails, BrotherList, UndergraduateList


urlpatterns = patterns('gtphipsi.rest.v1.brothers.views',
    url(r'^$', BrotherList.as_view(), name='brother_list'),
    url(r'^alumni/$', AlumnusList.as_view(), name='alumni_list'),
    url(r'^undergrads/$', UndergraduateList.as_view(), name='undergrad_list'),
    url(r'^(?P<badge>\d+)/$', BrotherDetails.as_view(), name='brother_details'),
)

urls.py
"""Root URL configuration for the gtphipsi web application.

All URIs are routed to this URL configuration, then possibly dispatched to other URL confs in this package's submodules.

"""

from django.conf.urls.defaults import patterns, url, include
from django.views.generic.simple import direct_to_template


# 'Global' pages. These are pages that don't fit neatly into one app (submodule) or another.
urlpatterns = patterns('gtphipsi.views',
    url(r'^$', 'home', name='home'),
    url(r'^login/$', 'sign_in', name='sign_in'),
    url(r'^logout/$', 'sign_out', name='sign_out'),
    url(r'^register/$', 'register', name='register'),
    url(r'^register/success/$', 'register_success', name='register_success'),
    url(r'^calendar/$', 'calendar', name='calendar'),
    url(r'^contact/$', 'contact', name='contact'),
    url(r'^contact/thanks/$', 'contact_thanks', name='contact_thanks'),
    url(r'^forbidden/$', 'forbidden', name='forbidden'),
    url(r'^forgot/$', 'forgot_password', name='forgot_password'),
    url(r'^reset/(?P<id>\d+)/$', 'reset_password', name='reset_password'),
    url(r'^reset/success/$', 'reset_password_success', name='reset_password_success'),
    url(r'^robots\.txt$', direct_to_template, {'template': 'robots.txt', 'mimetype': 'text/plain'}),
)

# Include other URL configurations for app-specific pages.
urlpatterns += patterns('',
     url(r'^brothers/', include('gtphipsi.brothers.urls')),
     url(r'^officers/', include('gtphipsi.officers.urls')),
     url(r'^rush/', include('gtphipsi.rush.urls')),
     url(r'^chapter/', include('gtphipsi.chapter.urls')),
     url(r'^forums/', include('gtphipsi.forums.urls')),
     url(r'^rest/v1/', include('gtphipsi.rest.v1.urls')),
)

# Hack - to continue to support the old rush schedule URI.
urlpatterns += patterns('gtphipsi.rush.views',
    url(r'^rushschedule\.php$', 'old_schedule', name='old_rush_schedule'),
)

brothers/forms.py
"""Forms for the gtphipsi.brothers package.

This module exports the following form classes:
    - UserForm
    - EditProfileForm
    - EditAccountForm
    - ChangePasswordForm
    - NotificationSettingsForm
    - PublicVisibilityForm
    - ChapterVisibilityForm

This module exports the following widget classes:
    - BrotherSelect

"""

import hashlib

from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.forms.widgets import Select

from gtphipsi.brothers.models import UserProfile, VisibilitySettings, MAJOR_CHOICES, STATUS_CHOICES, SUFFIX_CHOICES
from gtphipsi.common import get_all_big_bro_choices


class BrotherSelect(Select):
    """A select widget customized for members of the chapter (each option displays a brother's name and badge number)."""

    def render_option(self, selected_choices, option_value, option_label):
        """Render a single option (brother) in the format 'First Last ... badge' (e.g., 'George Burdell ... 0')."""
        new_label = ('%s ... %d' % (option_label, option_value) if option_value > 0 else option_label)
        return Select.render_option(self, selected_choices, option_value, new_label)

    def render_options(self, choices, selected_choices):
        """Render all options in the set of choices."""
        return Select.render_options(self, choices, selected_choices)


class UserForm(forms.Form):
    """A form to create new users and user profiles, including all fields for both models (User and UserProfile)."""

    first_name = forms.CharField(max_length=30)
    middle_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30)
    suffix = forms.ChoiceField(choices=SUFFIX_CHOICES, required=False)
    nickname = forms.CharField(max_length=30, required=False,
                               help_text='The name you prefer to be called (if different from your first name)')
    username = forms.CharField(max_length=30)
    password = forms.CharField(min_length=settings.MIN_PASSWORD_LENGTH, widget=forms.PasswordInput,
                               help_text=('Must be at least %d characters long' % settings.MIN_PASSWORD_LENGTH))
    confirm = forms.CharField(min_length=settings.MIN_PASSWORD_LENGTH, widget=forms.PasswordInput, label='Confirm password')
    badge = forms.IntegerField(min_value=1)
    status = forms.ChoiceField(choices=STATUS_CHOICES, initial='U')
    big_brother = forms.ChoiceField(choices=(), required=False, widget=BrotherSelect)
    major = forms.ChoiceField(choices=MAJOR_CHOICES, required=False)
    hometown = forms.CharField(max_length=50, required=False)
    current_city = forms.CharField(max_length=50, required=False)
    initiation = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, required=False)
    graduation = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, required=False)
    dob = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, required=False, label='Date of birth')
    email = forms.EmailField(required=True)
    phone = forms.RegexField(regex=r'^\d{3}-\d{3}-\d{4}$', min_length=12, max_length=12, required=False, help_text='XXX-XXX-XXXX')
    secret_key = forms.CharField(widget=forms.PasswordInput, help_text='Given to brothers by the webmaster')
    make_admin = forms.BooleanField(required=False, help_text='Check this box if you were given a separate admin password')
    admin_password = forms.CharField(widget=forms.PasswordInput, required=False)

    def __init__(self, data=None):
        """Initialize the form and set the list of choices for the 'big_brother' field."""
        super(UserForm, self).__init__(data=data)
        self.fields['big_brother'].choices = get_all_big_bro_choices()

    def clean_username(self):
        """Ensure that the user does not enter a user name that is already taken."""
        username = self.cleaned_data.get('username')
        if username is not None and User.objects.filter(username=username).count() > 0:
            self._errors['username'] = self.error_class(['That username is taken.'])
            del self.cleaned_data['username']
        return self.cleaned_data['username'] if 'username' in self.cleaned_data else None

    def clean_confirm(self):
        """Ensure that the user typed the same password in both the 'password' and 'confirm' fields."""
        password = self.cleaned_data.get('password')
        confirm = self.cleaned_data.get('confirm')
        if password is not None and confirm is not None and password != confirm:
            self._errors['confirm'] = self.error_class(['The passwords you typed do not match.'])
            del self.cleaned_data['confirm']
        return self.cleaned_data['confirm'] if 'confirm' in self.cleaned_data else None

    def clean_badge(self):
        """Ensure that the user does not enter a badge number that has already been used."""
        badge = self.cleaned_data.get('badge')
        if badge is not None and UserProfile.objects.filter(badge=badge).count() > 0:
            self._errors['badge'] = self.error_class(['A brother with that badge number already exists.'])
            del self.cleaned_data['badge']
        return self.cleaned_data['badge'] if 'badge' in self.cleaned_data else None

    def clean_big_brother(self):
        """Ensure that the user does not try to specify himself or a younger member as his big brother."""
        badge = self.cleaned_data.get('badge')
        big_bro_badge = int(self.cleaned_data.get('big_brother'))
        if badge is not None and big_bro_badge > 0:
            error = _get_big_bro_error_message(badge, big_bro_badge)
            if error is not None:
                self._errors['big_brother'] = self.error_class([error])
                del self.cleaned_data['big_brother']
        return self.cleaned_data['big_brother'] if 'big_brother' in self.cleaned_data else None

    def clean_secret_key(self):
        """Ensure that the user typed the correct secret key."""
        if 'secret_key' in self.cleaned_data:
            secret = self.cleaned_data.get('secret_key')
            if secret != settings.BROTHER_KEY:
                hash = hashlib.sha224(secret).hexdigest()
                if hash != settings.BROTHER_KEY:
                    self._errors['secret_key'] = self.error_class(['Nope!'])
                    del self.cleaned_data['secret_key']
        return self.cleaned_data['secret_key'] if 'secret_key' in self.cleaned_data else None

    def clean_admin_password(self):
        """Ensure that the user typed the correct administrator password if they checked the 'make admin' box."""
        if not self.cleaned_data.get('make_admin'):
            return ''   # if admin box is unchecked, validate by default
        if 'admin_password' in self.cleaned_data:
            password = self.cleaned_data.get('admin_password')
            if password != settings.ADMIN_KEY:
                hash = hashlib.sha224(password).hexdigest()
                if hash != settings.ADMIN_KEY:
                    self._errors['admin_password'] = self.error_class(['Wrong.'])
                    del self.cleaned_data['admin_password']
        return self.cleaned_data['admin_password'] if 'admin_password' in self.cleaned_data else None


class EditProfileForm(forms.ModelForm):
    """A form to modify user profiles, based on the UserProfile model class.

    The 'middle_name', 'suffix', 'nickname', and 'status' fields are excluded from the form. These fields are located
    in the EditAccountForm instead. The 'badge' and 'user' fields never change, and the visibility settings can be
    modified using the forms for the pertinent models (ChapterVisibilityForm and PublicVisibilityForm).

    """

    big_brother = forms.ChoiceField(choices=(), required=False, widget=BrotherSelect)
    initiation = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.DateInput(format='%B %d, %Y'),
                                 required=False)
    graduation = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.DateInput(format='%B %d, %Y'),
                                 required=False)
    dob = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.DateInput(format='%B %d, %Y'),
                          required=False, label='Date of birth')
    phone = forms.RegexField(regex=r'^\d{3}-\d{3}-\d{4}$', min_length=12, max_length=12, required=False, help_text='XXX-XXX-XXXX')

    def __init__(self, data=None, instance=None):
        """Initialize the form and set the list of choices for the 'big_brother' field."""
        super(EditProfileForm, self).__init__(data=data, instance=instance)
        self.fields['big_brother'].choices = get_all_big_bro_choices()

    def clean_big_brother(self):
        """Ensure that the user does not try to specify himself or a younger member as his big brother."""
        big_bro_badge = int(self.cleaned_data.get('big_brother'))
        if self.instance is not None and big_bro_badge > 0:
            error = _get_big_bro_error_message(self.instance.badge, big_bro_badge)
            if error is not None:
                self._errors['big_brother'] = self.error_class([error])
                del self.cleaned_data['big_brother']
        return self.cleaned_data['big_brother'] if 'big_brother' in self.cleaned_data else None

    class Meta:
        """Associate the form with the UserProfile model."""
        model = UserProfile
        fields = ('big_brother', 'major', 'hometown', 'current_city', 'initiation', 'graduation', 'dob', 'phone')


class EditAccountForm(forms.Form):
    """A form to modify user accounts and some data about user profiles (middle name, suffix, nickname, and status)."""

    first_name = forms.CharField(max_length=30)
    middle_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30)
    suffix = forms.ChoiceField(choices=SUFFIX_CHOICES, required=False)

rest/v1/brothers/views.py
from django.shortcuts import get_object_or_404

from gtphipsi.brothers.models import UserProfile
from gtphipsi.rest.v1.brothers.serializers import BrotherSerializer, NestedBrotherSerializer
from gtphipsi.rest.v1.views import RequestAwareListAPIView, RequestAwareRetrieveAPIView


class BaseBrotherList(RequestAwareListAPIView):
    serializer_class = NestedBrotherSerializer

    @staticmethod
    def get_badges(queryset):
        return queryset.values_list('badge', flat=True)


class BrotherList(BaseBrotherList):
    queryset = BaseBrotherList.get_badges(UserProfile.objects.all())


class AlumnusList(BaseBrotherList):
    queryset = BaseBrotherList.get_badges(UserProfile.objects.filter(status='A'))


class UndergraduateList(BaseBrotherList):
    queryset = BaseBrotherList.get_badges(UserProfile.objects.filter(status='U'))


class BrotherDetails(RequestAwareRetrieveAPIView):
    queryset = UserProfile.objects.all()
    serializer_class = BrotherSerializer

    def get_instance(self, **kwargs):
        return get_object_or_404(self.get_serializer_class().Meta.model, badge=kwargs['badge'])

templates/brothers/add.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Add New Brother | {{ block.super }}
{% endblock %}

{% block sidebar %}
    <h3>Note</h3>
    <p>This form should only be used when absolutely necessary. If possible, the brother should create
    an account on his own by visiting <a class="alwaysgreen" href="{% url 'gtphipsi.views.register' %}">this link</a>.
    (The link won't work when you are signed in, but it will work for someone who is not already registered.)</p>
{% endblock %}

{% block content %}
    <h1>Add New Brother</h1>
    <p>Use this form to add a new brother. Fields in bold are required.</p>
    <form action="{% url 'gtphipsi.brothers.views.add' %}" method="post">
        {% csrf_token %}
        <table class="form">
            <tbody>
                {% include "snippets/_registration_form.html" %}
                <tr>
                    <td class="spaced"></td>
                    <td class="spaced" style="padding-top: 10px">
                        {{ form.make_admin }} Make this user an administrator.
                    </td>
                    <td class="error small">
                        <ul>
                            {% for error in form.make_admin.errors %}
                                <li>{{ error|escape }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <input class="submit" type="submit" value="Add" />
                    </td>
                </tr>
            </tbody>
        </table>
    <input type="hidden" id="id_secret_key" name="secret_key" value="{{ secret_key }}" />
    <input type="hidden" id="id_admin_password" name="admin_password" value="{{ admin_password }}" />
    </form>
{% endblock %}

templates/brothers/change_email_success.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Email Address Changed | {{ block.super }}
{% endblock %}

{% block head_extras %}
    {{ block.super }}
    <script type="text/javascript">
        window.setTimeout(function() {
            window.location.href = '/';
        }, 10000);
    </script>
{% endblock %}

{% block content %}
    <h1>Email Changed Successfully</h1>
    <p>Your email address has been changed. Click <a href="{% url 'gtphipsi.views.home' %}">here</a> to go to the home page,
        or you will be automatically redirected there after ten seconds.</p>
{% endblock %}

templates/brothers/change_password.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Change Password | {{ block.super }}
{% endblock %}

{% block sidebar %}
    <h3>Note</h3>
    <p>Keep in mind that a longer password is more difficult to guess. It's also a good idea not to reuse passwords,
    especially the passwords you use for your email and bank accounts.</p>
{% endblock %}

{% block content %}
    <h1>Change Password</h1>
    <p>{% if message %}
        {{ message }}
        {% else %}
        Use the form below to change your password. Click "Save" when you are finished.
        {% endif %}
    </p>
    <form action="{% url 'gtphipsi.brothers.views.change_password' %}" method="post">
        {% include "snippets/_table_form.html" with submit_text="Save" %}
    </form>
{% endblock %}

templates/brothers/change_password_success.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Password Changed | {{ block.super }}
{% endblock %}

{% block content %}
    <h1>Password Changed Successfully</h1>
    <p>Your password has been changed. Click <a href="{% url 'gtphipsi.brothers.views.my_profile' %}">here</a> to go to your profile.</p>
{% endblock %}

templates/brothers/edit.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Edit User Profile | {{ block.super }}
{% endblock %}

{% block content %}
    <h1>Edit User Profile</h1>
    <p>Use the form below to edit your user profile. Click "Save" when you are finished.</p>
    <p>You may also want to <a class="alwaysgreen" href="{% url 'gtphipsi.brothers.views.edit_account' %}">edit your account details</a> or <a class="alwaysgreen" href="{% url 'gtphipsi.brothers.views.change_password' %}">change your password</a>.</p>
    <form action="{% url 'gtphipsi.brothers.views.edit' %}" method="post">
        {% include "snippets/_table_form.html" with submit_text="Save" %}
    </form>
{% endblock %}

templates/brothers/edit_group_members.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Edit Group Members | {{ block.super }}
{% endblock %}

{% block head_extras %}
    {{ block.super }}
    <style type="text/css">
        #content form ul li {
            list-style-type: none;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>Edit Members of Group "{{ group.name }}"</h1>
    <p>Use the checkboxes below to change the members associated with the user group <b>{{ group.name }}</b>. Click "Save" when you are finished.</p>
    <form action="{% url 'gtphipsi.brothers.views.edit_group_members' id=group.id %}" method="post">
        {% csrf_token %}
        <ul id="members_list">
        {% for id, name in choices %}
            <li><input type="checkbox" name="user_{{ id }}" value="{{ id }}" {% if id in initial %}checked{% endif %}/> {{ name }}</li>
        {% endfor %}
        </ul>
        <input class="submit" type="submit" value="Save" />
    </form>
{% endblock %}

templates/brothers/edit_visibility.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Edit {{ type|capfirst }} Privacy Settings | {{ block.super }}
{% endblock %}

{% block sidebar %}
    {% ifequal type 'chapter' %}
        <h3>Note</h3>
        <p>If you hide information from your chapter profile, not even you can see it when you view your profile.
        So why provide that information if you're just going to hide it from everyone?</p>
        <p>If you find that you have provided some information that you don't want anyone to see, simply edit your user profile and remove it.</p>
    {% else %}
        {{ block.super }}
    {% endifequal %}
{% endblock %}

{% block content %}
    <h1>Edit {{ type|capfirst }} Privacy Settings</h1>
    <p>Use this form to change what information is visible on your {{ type }} profile. {{ message }}</p>
    {% ifequal type 'public' %}
    <p><span style="font-weight: bold">Note:</span> {{ name_msg }}</p>
    {% endifequal %}
    <form action="{% ifequal type 'public' %}{% url 'gtphipsi.brothers.views.edit_public_visibility' %}{% else %}{% url 'gtphipsi.brothers.views.edit_chapter_visibility' %}{% endifequal %}" method="post">
        {% csrf_token %}
        <table class="form">
            <tbody>
            {% for field in form %}
                {% if field.label in fields %}
                <tr>
                    <td class="spaced">
                        {{ field.label_tag }}
                    </td>
                    <td class="spaced">
                        {{ field }}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
            <tr>
                <td colspan="3">
                    <input class="submit" type="submit" value="Save" />
                </td>
            </tr>
            </tbody>
        </table>
    </form>
{% endblock %}

templates/brothers/list.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}
    Chapter Brothers | {{ block.super }}
{% endblock %}

{% block content %}
    <h1>The Brothers</h1>
    {% ifequal num_undergrads 0 %}
        <p>There is currently no available information about the chapter's members. Please check back later.</p>
    {% else %}
        <p>The chapter currently has {{ num_undergrads }} undergraduate brother{{ num_undergrads|pluralize }}. The following is a list of the chapter's current active membership as well as a list of the chapter's alumni below that.</p>
        <table width="100%">
            <tbody>
            {% for row in undergrad_rows %}
                <tr>
                    {% for data in row %}
                        {% with badge=data.0 name=data.1 has_profile=data.2 %}
                            <td width="{{ col_width }}%">{% if data %}{% if has_profile %}<a class="hovercolor" href="{% url 'gtphipsi.brothers.views.show' badge=badge %}">{% endif %}{{ name }} ... {{ badge }}{% if has_profile %}</a>{% endif %}{% endif %}</td>
                        {% endwith %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <br />
        <hr>
        <br />
        <table width="100%">
            <tbody>
            {% for row in alumni_rows %}
                <tr>
                    {% for data in row %}
                        {% with badge=data.0 name=data.1 has_profile=data.2 %}
                            <td width="{{ col_width }}%">{% if data %}{% if has_profile %}<a class="hovercolor" href="{% url 'gtphipsi.brothers.views.show' badge=badge %}">{% endif %}{{ name }} ... {{ badge }}{% if has_profile %}</a>{% endif %}{% endif %}</td>
                        {% endwith %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endifequal %}
{% endblock %}

templates/brothers/notification_settings.html
{% extends "base_bros_only.html" %}
{% load url from future %}

{% block title %}
    Edit Notification Settings | {{ block.super }}
{% endblock %}

{% block head_extras %}
    {{ block.super }}
    <style type="text/css">
        #content form table tbody tr td label {
            width: auto;
        }
    </style>
{% endblock %}

{% block sidebar %}
    <h3>Note</h3>
    <p>Notification emails will be sent from <span style="font-weight: bold">{{ from_email }}</span>. If you
    elect to receive notifications, make sure this email address is not blocked by your email account's junk or spam filters.</p>
{% endblock %}

{% block content %}
    <h1>Notification Settings</h1>
    <p>Use the checkboxes below to control the notifications you receive from this site.</p>
    <p>Notifications will be sent to <b>{{ email }}</b>. Click <a href="{% url 'gtphipsi.brothers.views.edit_account' %}">here</a> to update your email address.</p>
    <p style="margin: 35px 0 0 0"><b><i>Email me when . . .</i></b></p>
    <form action="{% url 'gtphipsi.brothers.views.edit_notification_settings' %}" method="post">
        {% csrf_token %}
        {% include "snippets/_table_form.html" with submit_text="Save" %}
    </form>
{% endblock %}

templates/brothers/register.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}
    Create an Account | {{ block.super }}
{% endblock %}

{% block head_extras %}
    <style type="text/css">
        #admin_password {
            display: none;
        }
        #badge input {
            width: 50px;
            max-width: 50px;
        }
    </style>
    <script type="text/javascript">
        function toggleAdminPassword() {
            var pwInput = document.getElementById('admin_password');
            if (pwInput.style.display != 'table-row') {
                pwInput.style.display = 'table-row';
            } else {
                pwInput.style.display = 'none';
            }
            return !document.getElementById("admin_password").checked;
        }
    </script>
{% endblock %}

{% block sidebar %}
    <h3>Note</h3>
    <p>You are welcome to provide as much or as little personal information as you like. You can always add, change, or
    remove it later. You will also be able to control what information is visible to visitors of the site and what is
    visible to other brothers.</p>
{% endblock %}

{% block content %}
    <h1>Create an Account</h1>
    <p>Use this form to create an account. Fields in bold are required.</p>
    <form action="{% url 'gtphipsi.views.register' %}" method="post">
        {% csrf_token %}
        <table class="form">
            <tbody>
                {% include "snippets/_registration_form.html" %}
                <tr>
                    <td colspan="3" style="font-weight: bold; font-size: 1.1em; border-bottom: 2px solid black; margin-bottom: 15px">Proof of Membership</td>
                </tr>
                <tr>
                    <td {% if form.secret_key.errors %}class="error"{% endif %} style="font-weight: bold">
                        {{ form.secret_key.label_tag }}
                    </td>
                    <td style="padding-top: 10px">
                        {{ form.secret_key }}
                    </td>
                    <td class="error small">
                        <ul>
                            {% for error in form.secret_key.errors %}
                                <li>{{ error|escape }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td class="help-text small">
                        {{ form.secret_key.help_text }}
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="checkbox" id="id_make_admin" name="make_admin" onclick="return toggleAdminPassword();" /> Make me an administrator.
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td class="help-text small">
                        {{ form.make_admin.help_text }}
                    </td>
                    <td></td>
                </tr>
                <tr id="admin_password">
                    <td {% if form.admin_password.errors %}class="error spaced"{% else %}class="spaced"{% endif %}><label for="id_admin_password">Admin password</label></td>
                    <td class="spaced"><input type="password" id="id_admin_password" name="admin_password" /></td>
                    <td class="error small">
                        <ul>
                            {% for error in form.admin_password.errors %}
                                <li>{{ error|escape }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <input class="submit" type="submit" value="Register" />
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
{% endblock %}